### ISSUE TITLE
本地部署一直有问题

### ISSUE THREAD

**Issue by Grenemal** [doocs/md#466]
在运行本地部署的时候有问题

```
PS D:\Users\Wanju\Documents\GitHub\doocsmd> npm run build

> md@1.6.0 build
> run-p type-check "build:only {@}" --


> md@1.6.0 type-check
> vue-tsc --build --force


> md@1.6.0 build:only
> vite build

vite v5.4.11 building for production...
transforming (1) index.html
warn - You have enabled experimental features: optimizeUniversalDefaults
warn - Experimental features in Tailwind CSS are not covered by semver, may introduce breaking changes, and can change at any time.
(node:1496) ExperimentalWarning: CommonJS module D:\Users\Wanju\Documents\GitHub\doocsmd\node_modules\tailwindcss\lib\lib\load-config.js is loading ES Module D:\Users\Wanju\Documents\GitHub\doocsmd\tailwind.config.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///D:/Users/Wanju/Documents/GitHub/doocsmd/tailwind.config.js:1
const animate = require(`tailwindcss-animate`)
                ^

ReferenceError: require is not defined
    at file:///D:/Users/Wanju/Documents/GitHub/doocsmd/tailwind.config.js:1:17
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:395:35)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:329:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1376:24)
    at Module._compile (node:internal/modules/cjs/loader:1528:5)
    at node:internal/modules/cjs/loader:1698:10
    at transformer (file:///D:/Users/Wanju/Documents/GitHub/doocsmd/node_modules/tsx/dist/register-C3TE0KFF.mjs:2:748)
    at Object.transformer [as .js] (file:///D:/Users/Wanju/Documents/GitHub/doocsmd/node_modules/tsx/dist/register-C3TE0KFF.mjs:2:748)
    at Module.load (node:internal/modules/cjs/loader:1303:32)
    at Function._load (node:internal/modules/cjs/loader:1117:12)

Node.js v23.3.0
ERROR: "build:only" exited with 1.
```
我查看了代码，将tailwind.config.js种的
···
const animate = require(`tailwindcss-animate`)
```
按照vscode的建议改成了
```
import animate from `tailwindcss-animate`
```
结果就出现
···
PS D:\Users\Wanju\Documents\GitHub\doocsmd> npm run build

> md@1.6.0 build
> run-p type-check "build:only {@}" --


> md@1.6.0 type-check
> vue-tsc --build --force


> md@1.6.0 build:only
> vite build

vite v5.4.11 building for production...
✓ 1 modules transformed.
(node:6832) ExperimentalWarning: CommonJS module D:\Users\Wanju\Documents\GitHub\doocsmd\node_modules\tailwindcss\lib\lib\load-config.js is loading ES Module D:\Users\Wanju\Documents\GitHub\doocsmd\tailwind.config.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
x Build failed in 168ms
error during build:
[vite:css] [postcss] Expected string token at the end of import statement.
file: D:/Users/Wanju/Documents/GitHub/doocsmd/index.html?html-proxy&inline-css&index=0.css:undefined:NaN
    at CJSImportProcessor.preprocessImportAtIndex (D:\Users\Wanju\Documents\GitHub\doocsmd\node_modules\sucrase\dist\CJSImportProcessor.js:239:13)
    at CJSImportProcessor.preprocessTokens (D:\Users\Wanju\Documents\GitHub\doocsmd\node_modules\sucrase\dist\CJSImportProcessor.js:56:14)
    at getSucraseContext (D:\Users\Wanju\Documents\GitHub\doocsmd\node_modules\sucrase\dist\index.js:121:21)
    at transform (D:\Users\Wanju\Documents\GitHub\doocsmd\node_modules\sucrase\dist\index.js:38:28)
    at Object.transform (D:\Users\Wanju\Documents\GitHub\doocsmd\node_modules\tailwindcss\lib\lib\load-config.js:38:43)
    at D:\Users\Wanju\Documents\GitHub\doocsmd\node_modules\jiti\dist\jiti.js:1:242901
    at opts.transform.Object.assign.Object.assign.Object.assign.legacy (D:\Users\Wanju\Documents\GitHub\doocsmd\node_modules\jiti\dist\jiti.js:1:242722)
    at transform (D:\Users\Wanju\Documents\GitHub\doocsmd\node_modules\jiti\dist\jiti.js:1:242844)
    at evalModule (D:\Users\Wanju\Documents\GitHub\doocsmd\node_modules\jiti\dist\jiti.js:1:246228)
    at jiti (D:\Users\Wanju\Documents\GitHub\doocsmd\node_modules\jiti\dist\jiti.js:1:245241)
ERROR: "build:only" exited with 1.
···
然后就不知道怎么修改了
求大佬指点

**Comment by YangFong** [comment]
Node 版本问题，当前项目推荐使用 v20。

v22 以及上使用有点问题，需等待更新。
